renovatebot/pep440

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md

- Create issue templates for bugs and features
- Create pull request template
- Create `config.yml` file that redirects users needing help with Renovat bot config
- Disable blank issues within `config.yml` file
This work is basically copy/pasted from https://github.com/renovatebot/renovatebot.github.io with some changes.

chore: create issue and PR templates, create config.yml

---

README.md

- Copy/paste description from `package.json` into README.md
This should probably be expanded by somebody who knows what this repo is supposed to do.
At least we have some explanation now.

chore: add description to README

---

.github/workflows/build.yml

add actions build

---

README.md

- Add a badge that displays the test status in the readme
I like having those badges. 😄

chore: add test status badge to readme

---

.github/workflows/build.yml

- Run tests on pushes to `main` instead of on pushes to `master`
I think we forgot to change this file when we migrated to `main`.

ci: master -> main

---

.github/workflows/build.yml

- Support cache of dependencies in setup-node.
- Fixes: #114

refactor: node install buildin cache

---

index.d.ts
lib/shared.d.ts
lib/specifier.d.ts
lib/version.d.ts

- Rename parsed to Pep440Version
- Fixes: #117

refactor: rename interfaces parsed and range 

---

index.d.ts
index.js

- Export type RANGE_PATTERN from `index.d.ts`
- Ref : comment by @viceice [link](https://github.com/renovatebot/pep440/pull/118#discussion_r781822907)

feat: export type RANGE_PATTERN

---

.github/workflows/build.yml

- Fix whitespace error
Not closing any existing issue with this.

chore: fix whitespace

---

.github/workflows/build.yml
codecov.yml
package.json

ci: add codecov

---

index.d.ts
lib/operator.d.ts
lib/operator.js
lib/semantic.d.ts
lib/shared.d.ts
lib/specifier.d.ts
lib/version.d.ts

- Re-export functions from `index.d.ts` instead of declaring again.
- closes #120

refactor: re-export functions from index.d.ts

---

.github/workflows/build.yml
.npmrc
.releaserc.json
package.json
yarn.lock

Adde semantic release like in renovate main repo
- closes #81

feat: add semantic release

---

lib/specifier.d.ts

- Updated name and type of parameter.
- Ref : #142

fix: update parameter type

---

.prettierignore

chore: ignore some files from prettier

---

package.json

BREAKING CHANGE: require node v14 or v16+

feat!: require node v14 or v16+

---

.husky/pre-commit
package.json
yarn.lock

- Setup pre-commit hook using husky
- Ref : #129

feat: setup pre-commit hook

---

.eslintrc.js
.github/pull_request_template.md
.github/workflows/build.yml
.husky/pre-commit
.lintstagedrc.json
.markdownlint-cli2.jsonc
README.md
jest.config.js
package.json
test/semantic.test.js
test/specifier.test.js
test/version.explain.test.js
test/version.test.js
tsconfig.json
tsconfig.lint.json
yarn.lock

setup full linting
- closes #129

build: update linting

---

.github/workflows/build.yml

ci: ignore engines for tests

---

lib/specifier.js
test/specifier.test.js

fix: Better `~=` comparison against the exactly same version

---

.prettierignore

chore(prettier): ignore pnpm-lock.yaml

---

.prettierrc.json
package.json
pnpm-lock.yaml

fix: use prettier-plugin-packagejson

---

lib/semantic.d.ts

Fixes the method declaration for `inc()`
Found while working on:  
- https://github.com/renovatebot/renovate/issues/16704

fix: correct type declaration for inc()

---

.github/workflows/build.yml

ci: add codecov token

---

.github/workflows/build.yml
jest.config.js
test/specifier.test.js

ci: use node v20

---

renovate.json

Don't release on dev deps updates

chore(renovate): drop rules

---

.github/workflows/build.yml

ci: don't stop main builds and use blob filter

---

.github/workflows/build.yml

ci: upload coverage

---

.github/workflows/build.yml
.npmrc

build: enable `provenance`

---

.github/actions/setup-node/action.yml
.github/workflows/build.yml

ci: fix job
